SELECT
    TRIM(id_plano)::INTEGER               AS id_plano,
    TRIM(cd_plano)::VARCHAR(20)           AS cd_plano,
    TRIM(nm_plano)::VARCHAR(255)          AS nm_plano,
    TRIM(registro_operadora)::INTEGER     AS registro_ans,
    TRIM(razao_social)::VARCHAR(255)      AS razao_social,
    TRIM(gr_modalidade)::VARCHAR(255)     AS gr_modalidade,
    TRIM(porte_operadora)::VARCHAR(30)    AS porte_operadora,
    TRIM(vigencia_plano)::VARCHAR(1)      AS vigencia_plano,
    TRIM(contratacao)::VARCHAR(255)       AS contratacao,
    TRIM(gr_contratacao)::VARCHAR(255)    AS gr_contratacao,
    TRIM(sgmt_assistencial)::VARCHAR(255) AS sgmt_assistencial,
    TRIM(gr_sgmt_assistencial)::VARCHAR(255) AS gr_sgmt_assistencial,
    TRIM(ig_odontologico)::VARCHAR(1)     AS ig_odontologico,
    TRIM(obstetricia)::VARCHAR(255)       AS obstetricia,
    TRIM(tipo_financiamento)::VARCHAR(255) AS tipo_financiamento,
    TRIM(abrangencia_cobertura)::VARCHAR(255) AS abrangencia_cobertura,
    TRIM(id_geo_cobertura)::VARCHAR(255)  AS id_geo_cobertura,
    TRIM(fator_moderador)::VARCHAR(255)   AS fator_moderador,
    TRIM(acomodacao_hospitalar)::VARCHAR(30) AS acomodacao_hospitalar,
    TRIM(livre_escolha)::VARCHAR(100)     AS livre_escolha,
    TRIM(situacao_plano)::VARCHAR(20)     AS situacao_plano,
    TRIM(dt_situacao)::DATE               AS dt_situacao,
    TRIM(dt_registro_plano)::DATE         AS dt_registro_plano,
    TRIM(dt_atualizacao)::DATE            AS dt_atualizacao
FROM {{source('stage', 'caracteristicas_produtos_suplementares') }}